default: &default
  adapter: postgresql
  encoding: unicode
  database: four_color_bot_development
  host: localhost
  pool: 5

development:
  <<: *default
  username: postgres

test:
  <<: *default
  database: four_color_bot_test
  username: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
